name: CI + PR summary

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint & Type-check & Build
        run: |
          npm run lint
          npm run type-check   # або як у вас
          npm run build

      - name: PR Summary comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            ## ✔ CI Summary

            **ESLint:** Passed  
            **Type-check:** completed  
            **Build:** completed  

          append: false
          delete: false
          only_create: false
          only_update: false
          hide_details: false
          hide: false
